spring:
  devtools:
    restart:
      enabled: true
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/introduce_expert?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimmins3483@gmail.com
    password: pdjkbqosuaktkxao
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true